---
title: "Descripción"
output:
  html_document:
    css: ANALITICA_WEB.css
    fig_caption: yes
    highlight: pygments
#  theme: simplex   To have the TOC in Red
    toc: yes
    toc_float: yes
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Fecha de la ultima revisión
```{r echo=FALSE}

Sys.Date()
```

***

# ANALITCA WEBINARS

***
## Webinars Mensuales

La Fundación ANALITICA presenta Webinars sobre diversos temas de analisis cuantitativos. Los Webinars se ofrecen los segundo jueves de cada mes a las 7pm (AST).  Estas presentación son en español.


```{r include=FALSE}
library(tidyverse)
library(gt)
```


# Conferencias ofrecidas 

```{r}
calendario=tribble(
  ~Fecha, ~Año, ~Tema, ~Recurso,
  "9 de septiembre", 2021, "Introducción a RMarkdown", "Raymond L. Tremblay, PhD",
  "21 de octubre", 2021, "Introducción a RStudio Cloud", "Denny Fernández del Viso, PhD",
  "11 de novienbre", 2021, "Introducción a ggplot2", "Marijulie Martinez-Lozano, DrPH",
  "9 de diciembre", 2021, "Introducción a al paquete Leaflet", "Normandie González, Estudiante graduada",
  "13 de enero", 2022, "Introducción a Machine Learning", "Jeffrey Chan, Estudiante graduado",
  "10 de febrero", 2022, "Ecuaciones Estructurales", "Ernesto Rosario Hernández, PhD",
  "10 de marzo", 2022, "Métodos estadísticos robustos", "Ricardo Morenna, PhD",
  "14 de abril", 2022, "Regresiones beta", "Raymond L. Tremblay, PhD",
  "12 de  mayo", 2022, "Arte Generativo: El código como medio creativo", "Elio Ramos, PhD"
)
gt(calendario)
```


