---
output:
  html_document:
    css: ANALITICA_WEB.css
    fig_caption: yes
    highlight: pygments
   # theme: simplex
    toc: yes
    toc_float: yes
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style>
.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    background-color: #437d66;
}
</style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***

# ECUACIONES ESTRUTURALES

- Fecha del webinar: el 10 de febrero 2022
- Recurso: Dr. Ernerso Rosario-Hernández 
- Afiliación: **Ponce Health Science University**
- Email: erosario@psm.edu


## Tema:

 > El modelamiento de ecuaciones estructurales es una combinación de técnicas multivariadas entre las que se incluyen la regresión y el análisis de factores. Tiende a tener un enfoque confirmatorio, aunque también puede tomar un enfoque exploratorio. Tiene la ventaja de que puede trabajar con múltiples variables independientes y dependientes de forma simultánea, y toma en consideración el error de medición en sus estimados. También puede trabajar tanto con variables observadas como con variables latentes.
 
 
## Enlace a la presentación

 Para visualizar la presentación Power Point vea el siguiente [enlace](Power_point/Introduccion_SEM_Ernesto_Rosario.pptx). 
 
 
## Video

 Enlace para vizualizar la video de la presentación en el canal de Youtube


## Recursos suplementarios

Vea el siguiente enlace para más detalles sobre el tema [Gaskination](http://statwiki.gaskination.com/index.php?title=Main_Page)





 
 

